from reportlab.pdfgen import canvas
from datetime import datetime

def create_pdf(destination,days,budget,trip_category,temp,condition,tips,plan):
    
    filename = "Smart_Trip_Itinerary.pdf"
    pdf = canvas.Canvas(filename)
    y=800


    title = "SMART TRIP PLANNER"
    pdf.setFont("Helvetica-Bold", 20)

    title_width = pdf.stringWidth(title, "Helvetica-Bold", 20)
    pdf.drawString((595-title_width)/2, y, title)
    
    y-=40
    current_time = datetime.now().strftime("%d-%m-%Y %H:%M")
    pdf.drawString(50, y, f"Generated On: {current_time}")
    y-=40

    pdf.setFont("Helvetica-Bold", 15)

    pdf.drawString(50,y,"TRIP DETAILS")
    y-=25
    pdf.setFont("Helvetica", 12)
    pdf.drawString(70,y,f"Destination: {destination}")
    y-=20
    pdf.drawString(70,y,f"Duration: {days} Days")
    y-=20
    pdf.drawString(70,y,f"Budget: Rs {budget}")
    y-=20
    pdf.drawString(70,y,f"Trip Type: {trip_category}")
    y-=40

    pdf.setFont("Helvetica-Bold", 15)

    pdf.drawString(50,y,"CURRENT WEATHER")
    y-=25
    pdf.setFont("Helvetica", 12)
    pdf.drawString(70,y,f"Temperature: {temp} C")
    y-=20
    pdf.drawString(70,y,f"Condition: {condition}")
    y-=40

    pdf.setFont("Helvetica-Bold", 15)

    pdf.drawString(50,y,"BUDGET RECOMMENDATIONS")
    y-=25
    pdf.setFont("Helvetica", 12)
    for tip in tips:
        pdf.drawString(70,y,f"• {tip}")
        y-=20
    y-=20

    pdf.setFont("Helvetica-Bold", 15)

    pdf.drawString(50,y,"DAY-WISE ITINERARY")
    y-=30
    for day_num, day_places in enumerate(plan,start=1):
        pdf.setFont("Helvetica-Bold", 13)
        pdf.drawString(60,y,f"Day: {day_num}")
        y-=20
        pdf.setFont("Helvetica", 12)

        for place in day_places:
            pdf.drawString(80,y,f"• {place}")
            y-=20
        y-=10
    y-=20

    pdf.setFont("Helvetica-Oblique", 10)
    pdf.drawString(50,y,"Generated By Smart Trip Planner")

    pdf.save()

    return filename














    






    